version: '3'
services:

  order-svc:
    image: 'order'
    container_name: 'order-svc'
    command:
    - manage.py
    - runserver
    - 0.0.0.0:8001
    env_file:
    - ./order/config.env
    volumes:
    - ./order:/backend
    network_mode: host

  store-svc:
    image: 'store'
    container_name: 'store-svc'
    command:
    - manage.py
    - runserver
    - 0.0.0.0:8002
    build: .
    env_file:
    - ./store/config.env
    volumes:
    - ./store:/backend
    network_mode: host


  delivery-svc:
    image: 'delivery'
    container_name: 'delivery-svc'
    command:
    - manage.py
    - runserver
    - 0.0.0.0:8003
    build: .
    env_file:
    - ./delivery/config.env
    volumes:
    - ./delivery:/backend
    network_mode: host


networks:
  net: